### PR TITLE
AYON to ftrack sync: Sync comments

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Sync comments from AYON to ftrack and from ftrack to AYON.

## Additional review information
Both syncs are ONLY live, so if transmitter is not running or leecher is not running we might loose some commets meanwhile. Which I don't know how to "fix". I considr this as first version that is working in "base".

To avoid clashes I also had to remove Integrate note publish plugin which would cause doubled comments.

## Testing notes:
If running service tools, make sure to run `install` command first.
Make sure to use last server version.

1. Run all services.
2. Create comment on AYON/ftrack, validate those are propagated to ftrac/AYON.
3. Change/Remove them -> validate it is propagated to the other side.
4. Comments created during publishing should be pushed to both even if IntegrateNote plugins is not available anymore.

Resolves https://github.com/ynput/ayon-ftrack/issues/170

### CODE REVIEW

**Comment by 64qam** [comment]
Sync works both directions, editing and removing work only from Ftrack to Ayon (no errors available:-()

**Comment by iLLiCiTiT** [comment]
> editing and removing work only from Ftrack to Ayon (no errors available:-()

Editing issue seems to be related to server bug. The removement is something I didn't think about...

**Comment by iLLiCiTiT** [comment]
Editing should be fixed with current server develop.

**Comment by 64qam** [comment]
Ftrack to Ayon works well. The direction from Ftrack to Ayon also works. But: from Ayon to Ftrack, it only works if I sync only one way (only creating comment in Ayon). As soon as I write or change a comment in Ftrack, the next comment in Ayon won't pass to Ftrack.

**Comment by 64qam** [comment]
Still the same behaviour.
```2024-12-05 09:53:06 ERROR    Server reported error: IntegrityError(A note message must have recipients.)
NoneType: None
2024-12-05 09:53:06 WARNING  Failed to create Note
Traceback (most recent call last):
  File "C:\Users\qam\code\ayon-ftrack\services\transmitter\transmitter\logic.py", line 1088, in _create_ftrack_note
    self._session.commit()
  File "C:\Users\qam\code\ayon-ftrack\service_tools\venv\lib\site-packages\ftrack_api\session.py", line 1308, in commit
    result = self.call(batch)
  File "C:\Users\qam\code\ayon-ftrack\service_tools\venv\lib\site-packages\ftrack_api\session.py", line 1687, in call
    raise ftrack_api.exception.ServerError(error_message)
ftrack_api.exception.ServerError: Server reported error: IntegrityError(A note message must have recipients.)```

**Review by 64qam — APPROVED** [review]

**Pull request merged**
